name: Deploy to Netlify

on:
  push:
   branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout repository
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install
        
      - name: Build site
        run: yarn build

      # Deploy site to Netlify
      - name: Deploy site
        env:
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        run: netlify deploy --dir=public --prod
